spring:
  main:
    allow-circular-references: true
  application:
    name: JurassicParkMPI
  jpa:
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: false
    properties:
      hibernate:
        show_sql=false:
    hibernate:
      ddl-auto: update
  datasource:
    username: ${DB_USER:postgres}
    password: ${DB_PASS:896699}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/postgres
    driver-class-name: org.postgresql.Driver

jwt:
  secret: zerotwobestwaifu

server:
  port: ${PORT:8081}
